
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8507
  Network URL: http://172.31.40.84:8507
  External URL: http://3.108.70.93:8507

  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8506
  Network URL: http://172.31.40.84:8506
  External URL: http://3.108.70.93:8506

2025-07-23 14:46:51.825 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-23 14:46:51.830 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-23 14:49:23.663 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-23 14:49:23.669 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-24 05:23:02.128 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-24 05:23:02.135 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-24 05:23:02.142 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-24 05:23:02.149 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8506
  Network URL: http://172.31.40.84:8506
  External URL: http://3.108.70.93:8506

2025-07-25 05:55:53.741 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 05:55:53.750 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'Drayage' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:04:10.490 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:04:10.494 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'Drayage' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:11:46.312 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:11:46.316 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'FTL53' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.896 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.903 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.909 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.916 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.923 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 06:26:41.927 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 11:54:47.974 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 11:54:47.981 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 11:54:47.987 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-07-25 11:54:47.993 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8506
  Network URL: http://172.31.40.84:8506
  External URL: http://3.108.70.93:8506

2025-08-01 13:13:13.934 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-01 13:13:13.945 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'FTL53' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-01 13:17:13.097 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-01 13:17:13.103 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:08:56.759 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:08:56.766 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'FTL53' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:12:09.025 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:12:09.031 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'FTL53' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:25:51.562 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-02 09:25:51.568 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'FTL53' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:23:05.939 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 212, in fba_quote_app
    st.number_input("Quantity*", min_value=1, value=quantity_val, key=f"qty_{idx}_{row_idx}", disabled=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 410, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/elements/widgets/number_input.py", line 324, in number_input
    return self._number_input(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/elements/widgets/number_input.py", line 457, in _number_input
    raise StreamlitValueBelowMinError(value=value, min_value=min_value)
streamlit.errors.StreamlitValueBelowMinError: The `value` 0 is less than the `min_value` 1.
2025-08-04 06:26:15.169 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:26:15.175 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'Drayage' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.514 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.520 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.527 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'WARM' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.530 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.539 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'COLD' with type str: tried to convert to double", 'Conversion failed for column Value with type object')
2025-08-04 06:54:52.543 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert 'LTL' with type str: tried to convert to double", 'Conversion failed for column Value with type object')

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8506
  Network URL: http://172.31.40.84:8506
  External URL: http://3.108.70.93:8506

2025-08-06 11:25:39.220 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 310, in fba_quote_app
    styled_html1 = df.style\
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 1442, in style
    from pandas.io.formats.style import Styler
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/io/formats/style.py", line 44, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 164, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.1.2' or newer of 'jinja2' (version '3.0.3' currently installed).
2025-08-06 11:28:36.843 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 310, in fba_quote_app
    styled_html1 = df.style\
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 1442, in style
    from pandas.io.formats.style import Styler
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/io/formats/style.py", line 44, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 164, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.1.2' or newer of 'jinja2' (version '3.0.3' currently installed).

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8506
  Network URL: http://172.31.40.84:8506
  External URL: http://3.108.70.93:8506

2025-08-13 02:59:37.373 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 297, in fba_quote_app
    result, errors, skipped_fba = rates(
ValueError: not enough values to unpack (expected 3, got 2)
2025-08-13 03:01:51.676 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 297, in fba_quote_app
    result, errors, skipped_fba = rates(
ValueError: not enough values to unpack (expected 3, got 2)
/home/ubuntu/FBA-Pricing-Tool/pricing_calculation.py:490: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df["Pre-Determined Bucket"] = sub_df["Pre-Determined Bucket"].fillna("").astype(str).str.upper()
/home/ubuntu/FBA-Pricing-Tool/pricing_calculation.py:490: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df["Pre-Determined Bucket"] = sub_df["Pre-Determined Bucket"].fillna("").astype(str).str.upper()
2025-08-13 03:17:50.638 Uncaught app execution
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/FBA-Pricing-Tool/fba_main.py", line 17, in <module>
    fba_quote_app()
  File "/home/ubuntu/FBA-Pricing-Tool/calculator.py", line 297, in fba_quote_app
    result, errors, skipped_fba = rates(
ValueError: not enough values to unpack (expected 3, got 2)
